### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by lharri73** [lharri73/PySimlink#11]
This broke in the 1.2.0 release

**Comment by thetypingpuppy** [comment]
Any idea what caused the break / error message? Thanks for your efforts

**Comment by lharri73** [comment]
iirc window's implementation of importlib was throwing a very unhelpful error and then segfaulting in python (even before the module entrypoint) when importing the compiled library at runtime. I ended up digging through python source code and eventually gave up. 

I don't have regular access to a windows machine with a compiler so it's not easy for me to test on Windows anyway, but if you have an error for me to look at, I'd be happy to take a look now that I've gotten a few other updates in.
