### ISSUE TITLE
Cant run on two computers, win7(VS19, 2022a), win11(VS 22, 2024a). Same error: no 'nmake' '-?'

### ISSUE THREAD

**Issue by greglu1976** [lharri73/PySimlink#19]
log:
-- Configuring incomplete, errors occurred!
CMake Error at CMakeLists.txt:2 (project):
  Running

   'nmake' '-?'

  failed with:

   no such file or directory

CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage.

**Comment by lharri73** [comment]
This is saying cmake can't find 'nmake' (the Microsoft version of make). Did you install the "desktop development with c++" workload of visual studio? It should be included in that package.
